<a href="https://colab.research.google.com/github/12sandra/practice_problems_pybasics/blob/main/CaseStudy_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1) Import pandas, numpy
import numpy as np
import pandas as pd

In [2]:
#Load dataset using pd.read_csv()
df=pd.read_csv("/content/IMDB-Movie-Data.csv")

In [3]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

**Display: shape, head, column names, datatypes, missing values**

In [4]:
df.shape

(1000, 12)

In [5]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [6]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [7]:
df.dtypes

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

In [8]:
df.isnull()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,True,False
996,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,True,False
999,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
df.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

**Check and remove duplicates**

In [10]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [11]:
df.drop_duplicates(inplace = True)

In [12]:
df.duplicated().sum()

np.int64(0)

5) Rename columns ("Title" > "Movie_Title")

In [13]:
df.rename(columns={'Title': 'Movie_Title'}, inplace=True)
print(df)

     Rank              Movie_Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1       2               Prometheus  Adventure,Mystery,Sci-Fi
2       3                    Split           Horror,Thriller
3       4                     Sing   Animation,Comedy,Family
4       5            Suicide Squad  Action,Adventure,Fantasy
..    ...                      ...                       ...
995   996     Secret in Their Eyes       Crime,Drama,Mystery
996   997          Hostel: Part II                    Horror
997   998   Step Up 2: The Streets       Drama,Music,Romance
998   999             Search Party          Adventure,Comedy
999  1000               Nine Lives     Comedy,Family,Fantasy

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn
1    Following clues to the origin of mankind, a te...          Ridley Scott
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4    A secret government agency recruits some of th...            David Ayer
..                                                 ...                   ...
995  A tight-knit team of rising investigators, alo...             Billy Ray
996  Three American college students studying abroa...              Eli Roth
997  Romantic sparks occur between two dance studen...            Jon M. Chu
998  A pair of friends embark on a mission to reuni...        Scot Armstrong
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016
..                                                 ...   ...
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore
0                  121     8.1  757074              333.13       76.0
1                  124     7.0  485820              126.46       65.0
2                  117     7.3  157606              138.12       62.0
3                  108     7.2   60545              270.32       59.0
4                  123     6.2  393727              325.02       40.0
..                 ...     ...     ...                 ...        ...
995                111     6.2   27585                 NaN       45.0
996                 94     5.5   73152               17.54       46.0
997                 98     6.2   70699               58.01       50.0
998                 93     5.6    4881                 NaN       22.0
999                 87     5.3   12435               19.64       11.0

[1000 rows x 12 columns]

**6) Get unique genres**

In [14]:
df.Genre.unique()

array(['Action,Adventure,Sci-Fi', 'Adventure,Mystery,Sci-Fi',
       'Horror,Thriller', 'Animation,Comedy,Family',
       'Action,Adventure,Fantasy', 'Comedy,Drama,Music', 'Comedy',
       'Action,Adventure,Biography', 'Adventure,Drama,Romance',
       'Adventure,Family,Fantasy', 'Biography,Drama,History',
       'Animation,Adventure,Comedy', 'Action,Comedy,Drama',
       'Action,Thriller', 'Biography,Drama', 'Drama,Mystery,Sci-Fi',
       'Adventure,Drama,Thriller', 'Drama', 'Crime,Drama,Horror',
       'Action,Adventure,Drama', 'Drama,Thriller',
       'Action,Adventure,Comedy', 'Action,Horror,Sci-Fi',
       'Adventure,Drama,Sci-Fi', 'Action,Adventure,Western',
       'Comedy,Drama', 'Horror', 'Adventure,Drama,Fantasy',
       'Action,Crime,Thriller', 'Action,Crime,Drama',
       'Adventure,Drama,History', 'Crime,Horror,Thriller',
       'Drama,Romance', 'Comedy,Drama,Romance', 'Horror,Mystery,Thriller',
       'Crime,Drama,Mystery', 'Drama,Romance,Thriller',
       'Drama,History,Thriller', 'Action,Drama,Thriller', 'Drama,History',
       'Action,Drama,Romance', 'Drama,Fantasy', 'Action,Sci-Fi',
       'Adventure,Drama,War', 'Action,Comedy,Fantasy',
       'Biography,Comedy,Crime', 'Crime,Drama', 'Comedy,Crime,Drama',
       'Action,Comedy,Crime', 'Animation,Drama,Fantasy',
       'Horror,Mystery,Sci-Fi', 'Drama,Mystery,Thriller',
       'Crime,Drama,Thriller', 'Biography,Crime,Drama',
       'Crime,Mystery,Thriller', 'Action,Horror,Thriller',
       'Romance,Sci-Fi', 'Action,Fantasy,War', 'Action,Biography,Drama',
       'Drama,Horror,Mystery', 'Adventure,Drama,Family',
       'Adventure,Comedy,Romance', 'Action', 'Adventure,Crime,Mystery',
       'Comedy,Family,Musical', 'Adventure,Comedy,Drama',
       'Drama,Horror,Thriller', 'Drama,Music', 'Mystery,Thriller',
       'Mystery,Thriller,Western', 'Comedy,Family',
       'Biography,Comedy,Drama', 'Drama,Western', 'Drama,Mystery,Romance',
       'Action,Drama,Mystery', 'Action,Adventure,Crime',
       'Adventure,Sci-Fi,Thriller', 'Action,Comedy,Mystery',
       'Thriller,War', 'Action,Adventure,Thriller',
       'Drama,Fantasy,Romance', 'Action,Drama,History',
       'Animation,Adventure,Family', 'Adventure,Horror',
       'Drama,Romance,Sci-Fi', 'Action,Adventure,Family', 'Action,Comedy',
       'Comedy,Romance', 'Horror,Mystery', 'Drama,Family,Fantasy',
       'Sci-Fi', 'Drama,War', 'Drama,Fantasy,Horror',
       'Crime,Drama,History', 'Horror,Sci-Fi,Thriller',
       'Action,Drama,Sport', 'Adventure,Biography,Drama',
       'Biography,Drama,Thriller', 'Action,Adventure,Mystery',
       'Drama,Horror', 'Comedy,Crime', 'Drama,Fantasy,War',
       'Action,Adventure,Romance', 'Action,Drama,War',
       'Drama,Musical,Romance', 'Drama,Sci-Fi,Thriller',
       'Action,Drama,Sci-Fi', 'Drama,Sci-Fi', 'Adventure,Fantasy',
       'Thriller', 'Biography,Drama,Romance', 'Action,Adventure',
       'Action,Fantasy', 'Action,Drama,Horror', 'Comedy,Music,Romance',
       'Biography,Drama,Sport', 'Action,Horror', 'Comedy,Horror,Thriller',
       'Crime,Drama,Music', 'Action,Sci-Fi,Thriller',
       'Drama,Horror,Sci-Fi', 'Drama,Sport', 'Comedy,Horror',
       'Comedy,Fantasy,Romance', 'Comedy,Fantasy', 'Comedy,Drama,Fantasy',
       'Adventure,Comedy,Horror', 'Comedy,Mystery',
       'Action,Mystery,Sci-Fi', 'Action,Crime,Fantasy',
       'Comedy,Fantasy,Horror', 'Animation,Action,Adventure',
       'Action,Comedy,Family', 'Comedy,Sci-Fi', 'Action,Biography,Crime',
       'Adventure,Comedy', 'Comedy,Music', 'Comedy,Drama,Horror',
       'Action,Horror,Romance', 'Action,Drama,Fantasy',
       'Action,Mystery,Thriller', 'Action,Adventure,Horror',
       'Animation,Family,Fantasy', 'Adventure,Horror,Mystery',
       'Action,Horror,Mystery', 'Adventure,Comedy,Family',
       'Action,Crime,Mystery', 'Comedy,Drama,Family',
       'Action,Crime,Sport', 'Mystery,Sci-Fi,Thriller', 'Sci-Fi,Thriller',
       'Adventure,Drama,Horror', 'Biography,History,Thriller',
       'Adventure,Comedy,Sci-Fi', 'Fantasy,Horror',
       'Action,Fantasy,Thriller', 'Comedy,Romance,Sport',
       'Animation,Action,Comedy', 'Drama,Fantasy,Thriller',
       'Action,Comedy,Romance', 'Action,Fantasy,Horror',
       'Mystery,Romance,Sci-Fi', 'Comedy,Drama,Thriller',
       'Comedy,Western', 'Drama,History,War', 'Fantasy,Horror,Thriller',
       'Drama,Horror,Musical', 'Drama,Family', 'Romance,Sci-Fi,Thriller',
       'Animation,Fantasy', 'Drama,Mystery,War', 'Action,Drama,Family',
       'Adventure,Drama,Western', 'Drama,Music,Romance',
       'Comedy,Romance,Western', 'Adventure,Drama', 'Drama,Thriller,War',
       'Drama,Fantasy,Mystery', 'Comedy,Crime,Thriller',
       'Animation,Comedy,Drama', 'Action,Comedy,Sci-Fi',
       'Drama,Romance,War', 'Adventure,Fantasy,Mystery',
       'Mystery,Romance,Thriller', 'Biography,Drama,Mystery',
       'Animation,Drama,Romance', 'Comedy,Horror,Romance',
       'Action,Thriller,War', 'Action,Comedy,Horror',
       'Action,Crime,Sci-Fi', 'Crime,Thriller', 'Comedy,Horror,Sci-Fi',
       'Crime,Drama,Fantasy', 'Drama,Fantasy,Music',
       'Action,Comedy,Sport', 'Fantasy,Mystery,Thriller', 'Adventure',
       'Adventure,Biography', 'Adventure,Biography,Crime',
       'Comedy,Drama,Musical', 'Comedy,Family,Romance',
       'Biography,Drama,Family', 'Drama,Fantasy,Musical',
       'Adventure,Family', 'Adventure,Comedy,Fantasy',
       'Drama,Family,Music', 'Comedy,Family,Fantasy'], dtype=object)

In [15]:
df.Genre.value_counts()

Genre
Action,Adventure,Sci-Fi     50
Drama                       48
Comedy,Drama,Romance        35
Comedy                      32
Drama,Romance               31
                            ..
Drama,Fantasy,Musical        1
Adventure,Family             1
Adventure,Comedy,Fantasy     1
Drama,Family,Music           1
Comedy,Family,Fantasy        1
Name: count, Length: 207, dtype: int64

**7) Extract number of genres per movie**

In [16]:
df['no_of_genres']=df['Genre'].str.split(',').str.len()
df

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,no_of_genres
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,3
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,3
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,2
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,3
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0,3
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0,1
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0,3
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0,2
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0,3

In [17]:
df[['Movie_Title','Genre','no_of_genres']]

                 Movie_Title                     Genre  no_of_genres
0    Guardians of the Galaxy   Action,Adventure,Sci-Fi             3
1                 Prometheus  Adventure,Mystery,Sci-Fi             3
2                      Split           Horror,Thriller             2
3                       Sing   Animation,Comedy,Family             3
4              Suicide Squad  Action,Adventure,Fantasy             3
..                       ...                       ...           ...
995     Secret in Their Eyes       Crime,Drama,Mystery             3
996          Hostel: Part II                    Horror             1
997   Step Up 2: The Streets       Drama,Music,Romance             3
998             Search Party          Adventure,Comedy             2
999               Nine Lives     Comedy,Family,Fantasy             3

[1000 rows x 3 columns]

###8)Handle missing values in 'Revenue (Millions)' and 'Metascore

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Movie_Title         1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
 12  no_of_genres        1000 non-null   int64
dtypes: float64(3), int64(5), object(5)
memory usage: 101.7+ KB

In [19]:
df['Revenue (Millions)'].fillna(value=df['Revenue (Millions)'].mean(), inplace=True)
#missing values filled with mean

/tmp/ipython-input-307260753.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Revenue (Millions)'].fillna(value=df['Revenue (Millions)'].mean(), inplace=True)

In [20]:
df['Metascore'].fillna(value=df['Metascore'].median(), inplace=True)
print(df)
#Missing values filled with median

     Rank              Movie_Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1       2               Prometheus  Adventure,Mystery,Sci-Fi
2       3                    Split           Horror,Thriller
3       4                     Sing   Animation,Comedy,Family
4       5            Suicide Squad  Action,Adventure,Fantasy
..    ...                      ...                       ...
995   996     Secret in Their Eyes       Crime,Drama,Mystery
996   997          Hostel: Part II                    Horror
997   998   Step Up 2: The Streets       Drama,Music,Romance
998   999             Search Party          Adventure,Comedy
999  1000               Nine Lives     Comedy,Family,Fantasy

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn
1    Following clues to the origin of mankind, a te...          Ridley Scott
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4    A secret government agency recruits some of th...            David Ayer
..                                                 ...                   ...
995  A tight-knit team of rising investigators, alo...             Billy Ray
996  Three American college students studying abroa...              Eli Roth
997  Romantic sparks occur between two dance studen...            Jon M. Chu
998  A pair of friends embark on a mission to reuni...        Scot Armstrong
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016
..                                                 ...   ...
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore  \
0                  121     8.1  757074          333.130000       76.0
1                  124     7.0  485820          126.460000       65.0
2                  117     7.3  157606          138.120000       62.0
3                  108     7.2   60545          270.320000       59.0
4                  123     6.2  393727          325.020000       40.0
..                 ...     ...     ...                 ...        ...
995                111     6.2   27585           82.956376       45.0
996                 94     5.5   73152           17.540000       46.0
997                 98     6.2   70699           58.010000       50.0
998                 93     5.6    4881           82.956376       22.0
999                 87     5.3   12435           19.640000       11.0

     no_of_genres
0               3
1               3
2               2
3               3
4               3
..            ...
995             3
996             1
997             3
998             2
999             3

[1000 rows x 13 columns]

/tmp/ipython-input-855814914.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Metascore'].fillna(value=df['Metascore'].median(), inplace=True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Movie_Title         1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  1000 non-null   float64
 11  Metascore           1000 non-null   float64
 12  no_of_genres        1000 non-null   int64
dtypes: float64(3), int64(5), object(5)
memory usage: 101.7+ KB

**9) Top 5 movies by Rating**

In [22]:
sorted_df=df.sort_values(by="Rating",ascending=False)
sorted_df.head()
sorted_df[['Movie_Title','Rating']]

                 Movie_Title  Rating
54           The Dark Knight     9.0
80                 Inception     8.8
117                   Dangal     8.8
36              Interstellar     8.6
249         The Intouchables     8.6
..                       ...     ...
968                  Wrecker     3.5
647                 Tall Men     3.2
871     Dragonball Evolution     2.7
42   Don't Fuck in the Woods     2.7
829           Disaster Movie     1.9

[1000 rows x 2 columns]

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Movie_Title         1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  1000 non-null   float64
 11  Metascore           1000 non-null   float64
 12  no_of_genres        1000 non-null   int64
dtypes: float64(3), int64(5), object(5)
memory usage: 101.7+ KB

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Movie_Title         1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  1000 non-null   float64
 11  Metascore           1000 non-null   float64
 12  no_of_genres        1000 non-null   int64
dtypes: float64(3), int64(5), object(5)
memory usage: 101.7+ KB

 10) Movies with highest/lowest revenue

In [26]:
highest_revenue_movie = df.sort_values(by='Revenue (Millions)', ascending=False).head(1)
lowest_revenue_movie = df.sort_values(by='Revenue (Millions)', ascending=True).head(1)
highest_revenue_movie

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,no_of_genres
50,51,Star Wars: Episode VII - The Force Awakens,"Action,Adventure,Fantasy",Three decades after the defeat of the Galactic...,J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac, Domhna...",2015,136,8.1,661608,936.63,81.0,3

In [27]:
lowest_revenue_movie

,Rank,Movie_Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,no_of_genres
231,232,A Kind of Murder,"Crime,Drama,Thriller","In 1960s New York, Walter Stackhouse is a succ...",Andy Goddard,"Patrick Wilson, Jessica Biel, Haley Bennett, V...",2016,95,5.2,3305,0.0,50.0,3

 11 ) Average rating by Director

In [28]:
avg_rating_by_director = df.groupby('Director')['Rating'].mean()
print(avg_rating_by_director)

Director
Aamir Khan             8.50
Abdellatif Kechiche    7.80
Adam Leon              6.50
Adam McKay             7.00
Adam Shankman          6.30
                       ...
Xavier Dolan           7.55
Yimou Zhang            6.10
Yorgos Lanthimos       7.20
Zack Snyder            7.04
Zackary Adler          5.10
Name: Rating, Length: 644, dtype: float64

 12) Movies per year

In [29]:
movies_per_year=df.groupby('Year').size()
print(movies_per_year)

Year
2006     44
2007     53
2008     52
2009     51
2010     60
2011     63
2012     64
2013     91
2014     98
2015    127
2016    297
dtype: int64

13) Movies with rating > 8 & revenue > **100M**

In [36]:
movie_rev = df[(df['Rating'] > 8.0) & (df['Revenue (Millions)'] > 100.0)]
print(movie_rev[['Movie_Title', 'Rating', 'Revenue (Millions)']])

                                      Movie_Title  Rating  Revenue (Millions)
0                         Guardians of the Galaxy     8.1              333.13
6                                      La La Land     8.3              151.06
36                                   Interstellar     8.6              187.99
50     Star Wars: Episode VII - The Force Awakens     8.1              936.63
54                                The Dark Knight     9.0              533.32
67                             Mad Max: Fury Road     8.1              153.63
74                                       Zootopia     8.1              341.26
76                                   The Avengers     8.1              623.28
77                           Inglourious Basterds     8.3              120.52
80                                      Inception     8.8              292.57
82                        The Wolf of Wall Street     8.2              116.87
83                                      Gone Girl     8.1              167.74
92                                       The Help     8.1              169.71
99                                   The Departed     8.5              132.37
114  Harry Potter and the Deathly Hallows: Part 2     8.1              380.96
124                         The Dark Knight Rises     8.5              448.13
138                                Shutter Island     8.1              127.97
144                              Django Unchained     8.4              162.80
241                                    Inside Out     8.2              356.45
427                          The Bourne Ultimatum     8.1              227.14
499                                            Up     8.3              292.98
634                                        WALL·E     8.4              223.81
645                                   Gran Torino     8.2              148.09
688                                   Toy Story 3     8.3              414.98
772                      How to Train Your Dragon     8.1              217.39

 14)Group by Director: avg Rating, Revenue

In [37]:
director_info= df.groupby('Director').agg(
    Avg_Rating=('Rating', 'mean'),
    Avg_Revenue_Millions=('Revenue (Millions)', 'mean'))

print(director_info)

                     Avg_Rating  Avg_Revenue_Millions
Director
Aamir Khan                 8.50              1.200000
Abdellatif Kechiche        7.80              2.200000
Adam Leon                  6.50             82.956376
Adam McKay                 7.00            109.535000
Adam Shankman              6.30             78.665000
...                         ...                   ...
Xavier Dolan               7.55             43.223188
Yimou Zhang                6.10             45.130000
Yorgos Lanthimos           7.20              4.405000
Zack Snyder                7.04            195.148000
Zackary Adler              5.10              6.530000

[644 rows x 2 columns]

15) Group by Year: count, avg Rating

In [40]:
year_grp = df.groupby('Year').agg(
    Movie_Count=('Movie_Title', 'count'),
    Avg_Rating=('Rating', 'mean'))

print(year_grp)

      Movie_Count  Avg_Rating
Year
2006           44    7.125000
2007           53    7.133962
2008           52    6.784615
2009           51    6.960784
2010           60    6.826667
2011           63    6.838095
2012           64    6.925000
2013           91    6.812088
2014           98    6.837755
2015          127    6.602362
2016          297    6.436700

16) Create a new column Profitability:
a) Revenue divided by Duration
b) Find top 10 most profitable movies

In [41]:
df['Profitability'] = df['Revenue (Millions)'] / df['Runtime (Minutes)']
top_10_profit = df.sort_values(by='Profitability', ascending=False).head(10)
print(top_10_profit[['Movie_Title', 'Revenue (Millions)', 'Runtime (Minutes)', 'Profitability']])

                                    Movie_Title  Revenue (Millions)  \
50   Star Wars: Episode VII - The Force Awakens              936.63
85                               Jurassic World              652.18
119                                Finding Dory              486.29
87                                       Avatar              760.51
76                                 The Avengers              623.28
15                      The Secret Life of Pets              368.31
688                                 Toy Story 3              414.98
12                                    Rogue One              532.17
174                                      Frozen              400.74
797                             Despicable Me 2              368.05

     Runtime (Minutes)  Profitability
50                 136       6.886985
85                 124       5.259516
119                 97       5.013299
87                 162       4.694506
76                 143       4.358601
15                  87       4.233448
688                103       4.028932
12                 133       4.001278
174                102       3.928824
797                 98       3.755612

17) Create a column that categorizes movies by rating:
a) Rating < 6: Poor
b) 6 ≤ Rating < 7.5: Average
c) Rating ≥ 7.5: Excellent

In [42]:
conditions = [ df['Rating'] < 6,
    (df['Rating'] >= 6) & (df['Rating'] < 7.5),
    df['Rating'] >= 7.5]


values = ['Poor', 'Average', 'Excellent']

df['Rating_Category'] = np.select(conditions, values, default='Unknown')

print(df[['Movie_Title', 'Rating', 'Rating_Category']])

                 Movie_Title  Rating Rating_Category
0    Guardians of the Galaxy     8.1       Excellent
1                 Prometheus     7.0         Average
2                      Split     7.3         Average
3                       Sing     7.2         Average
4              Suicide Squad     6.2         Average
..                       ...     ...             ...
995     Secret in Their Eyes     6.2         Average
996          Hostel: Part II     5.5            Poor
997   Step Up 2: The Streets     6.2         Average
998             Search Party     5.6            Poor
999               Nine Lives     5.3            Poor

[1000 rows x 3 columns]

18) Create a custom function to score movies based on:
i) Apply row['Rating'] * 10 + row['Revenue (Millions)'] as High score
Apply a function to dataset to assign the score

In [43]:
def calculate_high_score(row):
    return (row['Rating'] * 10) + row['Revenue (Millions)']


df['High_Score'] = df.apply(calculate_high_score, axis=1)


scored_movies = df.sort_values(by='High_Score', ascending=False)

print(scored_movies[['Movie_Title', 'Rating', 'Revenue (Millions)', 'High_Score']])

                                    Movie_Title  Rating  Revenue (Millions)  \
50   Star Wars: Episode VII - The Force Awakens     8.1              936.63
87                                       Avatar     7.8              760.51
85                               Jurassic World     7.0              652.18
76                                 The Avengers     8.1              623.28
54                              The Dark Knight     9.0              533.32
..                                          ...     ...                 ...
27                                   Dead Awake     4.7                0.01
936        The Human Centipede (First Sequence)     4.4                0.18
237                    The Disappointments Room     3.9                2.41
871                        Dragonball Evolution     2.7                9.35
829                              Disaster Movie     1.9               14.17

     High_Score
50      1017.63
87       838.51
85       722.18
76       704.28
54       623.32
..          ...
27        47.01
936       44.18
237       41.41
871       36.35
829       33.17

[1000 rows x 4 columns]