<a href="https://colab.research.google.com/github/12sandra/practice_problems_pybasics/blob/main/spaceXcasestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import sqlite3
import requests
import numpy as np

In [ ]:
url = "https://api.spacexdata.com/v4/launches"
data = requests.get(url).json()

Data Exploration

In [ ]:
launch_data = pd.DataFrame(data)
launch_data.head(7)

,fairings,links,static_fire_date_utc,static_fire_date_unix,net,window,rocket,success,failures,details,...,date_utc,date_unix,date_local,date_precision,upcoming,cores,auto_update,tbd,launch_library_id,id
0,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,2006-03-17T00:00:00.000Z,1.142554e+09,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 33, 'altitude': None, 'reason': 'mer...",Engine failure at 33 seconds and loss of vehicle,...,2006-03-24T22:30:00.000Z,1143239400,2006-03-25T10:30:00+12:00,hour,False,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",True,False,None,5eb87cd9ffd86e000604b32a
1,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 301, 'altitude': 289, 'reason': 'har...",Successful first stage burn and transition to ...,...,2007-03-21T01:10:00.000Z,1174439400,2007-03-21T13:10:00+12:00,hour,False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",True,False,None,5eb87cdaffd86e000604b32b
2,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",Residual stage 1 thrust led to collision betwe...,...,2008-08-03T03:34:00.000Z,1217734440,2008-08-03T15:34:00+12:00,hour,False,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",True,False,None,5eb87cdbffd86e000604b32c
3,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,2008-09-20T00:00:00.000Z,1.221869e+09,False,0.0,5e9d0d95eda69955f709d1eb,True,[],Ratsat was carried to orbit on the first succe...,...,2008-09-28T23:15:00.000Z,1222643700,2008-09-28T11:15:00+12:00,hour,False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",True,False,None,5eb87cdbffd86e000604b32d
4,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,True,[],None,...,2009-07-13T03:35:00.000Z,1247456100,2009-07-13T15:35:00+12:00,hour,False,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",True,False,None,5eb87cdcffd86e000604b32e
5,"{'reused': None, 'recovery_attempt': None, 're...",{'patch': {'small': 'https://images2.imgbox.co...,2010-03-13T00:00:00.000Z,1.268438e+09,False,0.0,5e9d0d95eda69973a809d1ec,True,[],None,...,2010-06-04T18:45:00.000Z,1275677100,2010-06-04T14:45:00-04:00,hour,False,"[{'core': '5e9e289ef359185f2b3b2628', 'flight'...",True,False,None,5eb87cddffd86e000604b32f
6,None,{'patch': {'small': 'https://images2.imgbox.co...,2010-12-04T00:00:00.000Z,1.291421e+09,False,0.0,5e9d0d95eda69973a809d1ec,True,[],None,...,2010-12-08T15:43:00.000Z,1291822980,2010-12-08T11:43:00-04:00,hour,False,"[{'core': '5e9e289ef35918187c3b2629', 'flight'...",True,False,None,5eb87cdeffd86e000604b330

In [ ]:
launch_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   fairings               169 non-null    object
 1   links                  205 non-null    object
 2   static_fire_date_utc   121 non-null    object
 3   static_fire_date_unix  121 non-null    float64
 4   net                    205 non-null    bool
 5   window                 117 non-null    float64
 6   rocket                 205 non-null    object
 7   success                186 non-null    object
 8   failures               205 non-null    object
 9   details                134 non-null    object
 10  crew                   205 non-null    object
 11  ships                  205 non-null    object
 12  capsules               205 non-null    object
 13  payloads               205 non-null    object
 14  launchpad              205 non-null    object
 15  flight_number          205 non-null    int64
 16  name                   205 non-null    object
 17  date_utc               205 non-null    object
 18  date_unix              205 non-null    int64
 19  date_local             205 non-null    object
 20  date_precision         205 non-null    object
 21  upcoming               205 non-null    bool
 22  cores                  205 non-null    object
 23  auto_update            205 non-null    bool
 24  tbd                    205 non-null    bool
 25  launch_library_id      72 non-null     object
 26  id                     205 non-null    object
dtypes: bool(4), float64(2), int64(2), object(19)
memory usage: 37.8+ KB

In [ ]:
launch_data.size

5535

In [ ]:
launch_data.shape

(205, 27)

● Extract relevant columns: name, date_utc, success, details, rocket

In [ ]:
launch_data = launch_data[["name", "date_utc", "success", "details", "rocket"]]

In [ ]:
launch_data.shape

(205, 5)

Convert date_utc to datetime and extract the year

In [ ]:
launch_data["date_utc"] = pd.to_datetime(launch_data["date_utc"])

In [ ]:
launch_data["year"] = launch_data["date_utc"].astype(str).str.split("-").str[0]

In [ ]:
launch_data[["date_utc", "year"]].head()

                   date_utc  year
0 2006-03-24 22:30:00+00:00  2006
1 2007-03-21 01:10:00+00:00  2007
2 2008-08-03 03:34:00+00:00  2008
3 2008-09-28 23:15:00+00:00  2008
4 2009-07-13 03:35:00+00:00  2009

##Step 2: Load Rocket Metadata

In [ ]:
import requests
import pandas as pd

rocket_data = pd.DataFrame(requests.get("https://api.spacexdata.com/v4/rockets").json()
)

In [ ]:
rocket_data.columns

Index(['height', 'diameter', 'mass', 'first_stage', 'second_stage', 'engines',
       'landing_legs', 'payload_weights', 'flickr_images', 'name', 'type',
       'active', 'stages', 'boosters', 'cost_per_launch', 'success_rate_pct',
       'first_flight', 'country', 'company', 'wikipedia', 'description', 'id'],
      dtype='object')

In [ ]:
rocket_data = rocket_data[["id", "name", "type", "active", "stages"]]

In [ ]:
rocket_data.head()

                         id          name    type  active  stages
0  5e9d0d95eda69955f709d1eb      Falcon 1  rocket   False       2
1  5e9d0d95eda69973a809d1ec      Falcon 9  rocket    True       2
2  5e9d0d95eda69974db09d1ed  Falcon Heavy  rocket    True       2
3  5e9d0d96eda699382d09d1ee      Starship  rocket   False       2

In [ ]:
launch_data.head()

,name,date_utc,success,details,rocket,year
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009

#Step 3: Merge Launch and Rocket Data

In [ ]:
launches_data = launch_data.rename(columns={'name': 'launch_name'})
rockets_data = rocket_data.rename(columns={'name': 'rocket_name'})

In [ ]:
merged_df = pd.merge(
    launches_data,
    rockets_data,
    left_on='rocket',
    right_on='id',
    how='left'
)
(merged_df)

,launch_name,date_utc,success,details,rocket,year,id,rocket_name,type,active,stages
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2
...,...,...,...,...,...,...,...,...,...,...,...
200,Transporter-6,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,5e9d0d95eda69973a809d1ec,Falcon 9,rocket,True,2
201,TTL-1,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,5e9d0d95eda69973a809d1ec,Falcon 9,rocket,True,2
202,WorldView Legion 1 & 2,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,5e9d0d95eda69973a809d1ec,Falcon 9,rocket,True,2
203,Viasat-3 & Arcturus,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69974db09d1ed,2022,5e9d0d95eda69974db09d1ed,Falcon Heavy,rocket,True,2
204,O3b mPower 3.4,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022,5e9d0d95eda69973a809d1ec,Falcon 9,rocket,True,2

##Add Simulated Country Information

 Add a new column country and randomly assign one of these values: ['USA', 'Russia', 'India', 'China', 'France']

In [ ]:
countries = ['USA', 'Russia', 'India', 'China', 'France']

In [ ]:
merged_df['country'] = np.random.choice(countries, size=len(merged_df))

In [ ]:
(merged_df.head())

,launch_name,date_utc,success,details,rocket,year,id,rocket_name,type,active,stages,country
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,India
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,China
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,Russia
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,China
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,2,China

##Step 5: Store Merged Data in SQLite3

Use sqlite3 to create a connection and save the merged DataFrame as a table named launches

In [ ]:
conn = sqlite3.connect('launches.db')

In [25]:
conn = sqlite3.connect('launches.db')

In [26]:
merged_df.to_sql('launches', conn, index=False)

205

In [27]:
df_from_db = pd.read_sql('SELECT * FROM launches LIMIT 5', conn)
df_from_db

,launch_name,date_utc,success,details,rocket,year,id,rocket_name,type,active,stages,country
0,FalconSat,2006-03-24 22:30:00+00:00,0,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,0,2,India
1,DemoSat,2007-03-21 01:10:00+00:00,0,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,0,2,China
2,Trailblazer,2008-08-03 03:34:00+00:00,0,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,0,2,Russia
3,RatSat,2008-09-28 23:15:00+00:00,1,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,0,2,China
4,RazakSat,2009-07-13 03:35:00+00:00,1,None,5e9d0d95eda69955f709d1eb,2009,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,0,2,China

##Step 6: Run SQL Queries on the Data to analyze

1. Launches by Country

In [28]:
cursor=conn.cursor()

In [29]:
cursor.execute("""
     SELECT country, COUNT(*) AS launches_count
    FROM launches
    GROUP BY country
    ORDER BY launches_count DESC;
    """
)

In [30]:

rows=(cursor.fetchall())
for row in rows:
  print(row)

('USA', 45)
('Russia', 43)
('France', 41)
('India', 39)
('China', 37)

2. Which year had the highest number of launches?

In [31]:
cursor.execute("""
    SELECT year, COUNT(*) AS launches_count
    FROM launches
    GROUP BY year
    ORDER BY launches_count DESC
    LIMIT 1;
""")

In [32]:
row = cursor.fetchone()

In [33]:
print(row)

('2022', 62)

3. Top 5 Missions by Launch Count

In [38]:
cursor.execute("""
    SELECT launch_name, COUNT(*) AS launch_count
    FROM launches
    GROUP BY launch_name
    ORDER BY launch_count DESC
    LIMIT 5;
""")

In [39]:
rows = cursor.fetchall()
for row in rows:
  print(row)

('ispace Mission 1 & Rashid', 1)
('ZUMA', 1)
('WorldView Legion 1 & 2', 1)
('Viasat-3 & Arcturus', 1)
('USSF-44', 1)